
drop  table  FAKTURY
drop  table  KLIENCI
drop  table miasta
drop table GRUPY_KLIENTÓW


CREATE TABLE MIASTA (
NAZWA VARCHAR(50) PRIMARY KEY,
LICZBAMIESZKANCOW INT
)

CREATE TABLE GRUPY_KLIENTÓW (
SYMBOL VARCHAR(50) PRIMARY KEY,
NAZWAGRUPY VARCHAR(50),
DOMYSLNYRABAT VARCHAR(10)
)

CREATE TABLE KLIENCI
(
	REF INT PRIMARY KEY,
	NAZWA VARCHAR(50),
	MIASTO VARCHAR(50),
	GRUPAKLIENTA VARCHAR(50),
	FOREIGN KEY (MIASTO) REFERENCES MIASTA (NAZWA ),

	FOREIGN KEY (GRUPAKLIENTA) REFERENCES GRUPY_KLIENTÓW(SYMBOL )
);

CREATE TABLE FAKTURY 
(
	REF INT PRIMARY KEY,
	SYMBOL VARCHAR(50),
	DZIEN DATE,
	KLIENT INT,
	BRUTTO FLOAT,
	RABAT VARCHAR(50),
	FOREIGN KEY (KLIENT) REFERENCES KLIENCI(REF)
);