---JOINS

 CREATE TABLE MYEMPLOYEE (EMPLOYEEID INT, FIRSTNAME VARCHAR(20), LASTNAME VARCHAR(20))
 
 TRUNCATE TABLE MYEMPLOYEE
 
 INSERT INTO MYEMPLOYEE VALUES (1, 'Michael', 'Scott')
 INSERT INTO MYEMPLOYEE VALUES (2, 'Pam', 'Beesly')
 INSERT INTO MYEMPLOYEE VALUES (3, 'Dwight', 'Schrute')

 SELECT * FROM MYEMPLOYEE


 CREATE TABLE MYSALARY (EMPLOYEEID INT, SALARY FLOAT)

 INSERT INTO MYSALARY VALUES (1, 10000)
 INSERT INTO MYSALARY VALUES (2, 8000)
 INSERT INTO MYSALARY VALUES (3, 6000)

 SELECT * FROM MYSALARY
 SELECT * FROM MYEMPLOYEE

 SELECT FIRSTNAME, LASTNAME, SALARY fROM MYEMPLOYEE A INNER JOIN MYSALARY B ON A.EMPLOYEEID = B.EMPLOYEEID

  --LEFT OUTER JOIN
 CREATE TABLE MYPHONE (EMPLOYEEID INT, PHONNENUMBER INT)

 INSERT INTO MYPHONE VALUES (1, 1211123342)
 INSERT INTO MYPHONE VALUES (2, 1111111111)

 SELECT * FROM MYEMPLOYEE
 SELECT * FROM MYPHONE

 SELECT FIRSTNAME, LASTNAME, PHONNENUMBER FROM MYEMPLOYEE A LEFT JOIN MYPHONE B ON A.EMPLOYEEID = B.EMPLOYEEID

 --RIGHT JOINS
CREATE TABLE MYPARKING (EMPLOYEEID INT, PARKINGSPOT VARCHAR(20))

INSERT INTO MYPARKING VALUES (1, 'A1')
INSERT INTO MYPARKING VALUES (2, 'A2')

SELECT * FROM MYPARKING
SELECT * FROM MYEMPLOYEE

SELECT PARKINGSPOT, FIRSTNAME, LASTNAME  FROM MYPARKING A RIGHT JOIN MYEMPLOYEE B ON A.EMPLOYEEID = B.EMPLOYEEID

--FULL OUTER JOIN
CREATE TABLE MYCUSTOMER(CUSTOMERID INT, CUSTOMERNAME VARCHAR(20))

TRUNCATE TABLE MYCUSTOMER
INSERT INTO MYCUSTOMER VALUES (1, 'RAKESH')
INSERT INTO MYCUSTOMER VALUES (3, 'JOHN')

SELECT * FROM MYCUSTOMER

CREATE TABLE MYORDER (ORDERNUMBER INT, ORDERNAME VARCHAR(20), CUSTOMERID INT)

truncate table MYORDER
INSERT INTO MYORDER VALUES (1, 'SOMEORDER1', 1)
INSERT INTO MYORDER VALUES (2, 'SOMEORDER2', 2)
INSERT INTO MYORDER VALUES (3, 'SOMEORDER3', 7)
INSERT INTO MYORDER VALUES (4, 'SOMEORDER4', 8)

SELECT * FROM MYCUSTOMER
SELECT * FROM MYORDER

sELECT A.CUSTOMERID, A.CUSTOMERNAME, B.ORDERNAME, B.ORDERNUMBER 
FROM MYCUSTOMER A FULL OUTER JOIN MYORDER B ON A.CUSTOMERID = B.CUSTOMERID

SELECT GETDATE()

SELECT GETDATE() -2
SELECT DATEPART(yyyy, GETDATE()) AS YEARNUMBER

select DATEADD(day , 10, GETDATE())

use AdventureWorks2016CTP3
SELECT top 10 * FROM AdventureWorks2016CTP3.[Production].[WorkOrder]

SELECT WorkOrderID, ProductID, StartDate, EndDate,  DATEDIFF(day, StartDate, EndDate) 
FROM AdventureWorks2016CTP3.[Production].[WorkOrder]

--mysalary aggregate functions
SELECT * FROM MYSALARY
SELECT AVG(SALARY) FROM MYSALARY

SELECT COUNT(SALARY) FROM MYSALARY
SELECT SUM(SALARY) FROM MYSALARY
SELECT MIN(SALARY) FROM MYSALARY

--STRING FUNCTION
SELECT * FROM MYORDER
SELECT ORDERNUMBER, CONCAT('TEKST ', ORDERNAME) FROM MYORDER

SELECT ORDERNUMBER, CONCAT(RAND(), ORDERNAME) FROM MYORDER


--LEFT
SELECT ORDERNUMBER, ORDERNAME, LEFT(ORDERNAME, 5) FROM MYORDER

--RIGHT
SELECT ORDERNUMBER, ORDERNAME, RIGHT(ORDERNAME, 5) FROM MYORDER

--SUBSTRING
SELECT ORDERNUMBER, ORDERNAME, SUBSTRING(ORDERNAME, 2, 5) FROM MYORDER

--LOWERCASE
SELECT ORDERNUMBER, ORDERNAME, LOWER(ORDERNAME) FROM MYORDER

--LENGHT OF STRING
SELECT ORDERNUMBER, ORDERNAME, LEN(ORDERNAME) FROM MYORDER

SELECT ORDERNUMBER, ORDERNAME, CONCAT(UPPER(LEFT(ORDERNAME, 1)), LOWER(SUBSTRING(ORDERNAME, 2, LEN(ORDERNAME)))) FROM MYORDER




